# AI Init Development Environment Configuration
# Overrides for local development

project:
  environment: "development"
  debug_mode: true

# Development-specific settings
setup:
  force_overwrite: true  # Allow overwriting during dev
  verbose: true

installation:
  components:
    test_dashboard:
      default_port: 8085
      auto_start: true
      watch_mode: true

# Development workflow
workflow:
  auto_run_tests: true
  generate_coverage: true
  min_coverage: 80

# Enhanced logging
logging:
  level: "DEBUG"
  format: "pretty"
  output: "console"

# Git settings for dev
git:
  auto_stage: false  # Manual control in dev
  require_tests: true  # Must have tests passing

# Claude behavior in development
claude:
  verbose_explanations: true
  show_thinking: true
  interactive_mode: true
