# AI Init Production Configuration
# Overrides for production installations

project:
  environment: "production"
  debug_mode: false

# Production-specific settings
setup:
  force_overwrite: false  # Protect existing files
  backup_existing: true
  verbose: false

installation:
  components:
    test_dashboard:
      default_port: 8085
      auto_start: false  # Manual start in production
      watch_mode: false

# Production workflow
workflow:
  auto_run_tests: true
  generate_coverage: true
  min_coverage: 90  # Higher bar for production

# Minimal logging
logging:
  level: "INFO"
  format: "json"
  output: "file"
  file_path: "logs/ai_init.log"

# Git settings for production
git:
  auto_stage: false
  require_tests: true
  require_review: true  # Additional review step

# Claude behavior in production
claude:
  verbose_explanations: false
  show_thinking: false
  interactive_mode: false
  safety_checks: true
