# Base Configuration
# This is the lowest priority - provides defaults for all environments

system:
  name: "AI_SDLC"
  version: "1.0.0"

llm:
  providers:
    anthropic:
      api_base: "https://api.anthropic.com"
      default_model: "claude-3-5-sonnet-20241022"
      valid_models:
        - "claude-3-7-sonnet-20250219"
        - "claude-3-5-sonnet-20241022"
        - "claude-3-opus-20240229"

    openai:
      api_base: "https://api.openai.com/v1"
      default_model: "gpt-4o"
      valid_models:
        - "gpt-4o"
        - "gpt-4o-mini"

  default_provider: "anthropic"

  agents:
    discovery:
      provider: "anthropic"
      model: "claude-3-5-sonnet-20241022"
      temperature: 0
      # Reference external prompt file
      prompt: "file://prompts/discovery_agent.md"

    coder:
      provider: "anthropic"
      model: "claude-3-opus-20240229"
      temperature: 0
      # Reference external prompt file
      prompt: "file://prompts/coder_agent.md"

    solution_designer:
      provider: "anthropic"
      model: "claude-3-7-sonnet-20250219"
      temperature: 1
      # Could reference web-hosted prompt
      # prompt: "https://docs.example.com/prompts/solution_designer.md"
      prompt: "Design code modifications based on intent and discovered files."

orchestration:
  entry_team: "discovery"
  teams:
    discovery:
      name: "Discovery Team"
      tasks:
        - name: "discovery"
          agent: "discovery"
      routing:
        default: "solution"

    solution:
      name: "Solution Design Team"
      tasks:
        - name: "solution_designer"
          agent: "solution_designer"
      routing:
        default: "coder"

    coder:
      name: "Coder Team"
      tasks:
        - name: "coder"
          agent: "coder"
      routing:
        default: null

backup:
  enabled: true
  path: "workspaces/backups"

logging:
  level: "info"
  format: "structured"
