# Development Configuration
# This overrides base.yml for development environment

system:
  environment: "development"

llm:
  agents:
    # In dev, use faster/cheaper models
    discovery:
      model: "claude-3-5-sonnet-20241022"

    coder:
      model: "claude-3-5-sonnet-20241022"  # Override to use faster model

    solution_designer:
      model: "claude-3-5-sonnet-20241022"
      temperature: 0.7

logging:
  level: "debug"  # Verbose logging for development
  format: "pretty"

backup:
  path: "dev_backups"
  retention_days: 7  # Short retention in dev
